#!/bin/bash/
#----------------------------------------------------------------------
# Purpose:
#   To launch a set of queries to the IRSA TAP service dedicated to the 
#   HELP fields and the slphotdr4 tables at IRSA
#----------------------------------------------------------------------
# Parameters
#    $1 the name of the field  - purely to determine names of outputs
#    $2-$5 RAMIN, RAMAX, DECMIN, DECMAX - all in decimal degrees
#    $6 table name in IRSA (see irsa_tables.* or get latest versions from 
#    curl -o irsa_tables.fits "http://irsa.ipac.caltech.edu/TAP/sync?QUERY=SELECT+*+FROM+TAP_SCHEMA.tables&FORMAT=FITS"
#
#----------------------------------------------------------------------
# How to Improve:
#     might be nice to 
#
#----------------------------------------------------------------------
# Author(s): 
#    Seb Oliver (University of Sussex)
#----------------------------------------------------------------------
# Date: 
#    29th November 2015 (tested with commented header)
#----------------------------------------------------------------------
# Acknowledgement: 
#    This script was produced as part of the Herschel Extragalactic 
#    Legacy Project: HELP
#    The research leading to these results has received funding from the 
#    European Union Seventh Framework Programme FP7/2007-2013/ under 
#    grant agreement no 607254.”
#    "This publication reflects only the author’s view and the European 
#     Union is not responsible for any use that may be made of the 
#     information contained therein.” 
#----------------------------------------------------------------------
# end of header
#--

# this command is nice an quick and good for testing
HELP_tap_irsa_slphotdr4.csh SA13 197.6 198.5 42.407 43.020  slphotdr4


# the others will take longer
HELP_tap_irsa_slphotdr4.csh COSMOS 148.7 151.55 0.791 3.641 slphotdr4
HELP_tap_irsa_slphotdr4.csh GAMA-15 210.0 225.2 -2.530 3.433 slphotdr4
HELP_tap_irsa_slphotdr4.csh XMM-LSS 32.2 38.1 -7.454 -1.591  slphotdr4
HELP_tap_irsa_slphotdr4.csh Bootes 215.7 220.6 32.191 36.109  slphotdr4
HELP_tap_irsa_slphotdr4.csh CDFS-SWIRE 50.8 55.4 -30.439 -25.997 slphotdr4
HELP_tap_irsa_slphotdr4.csh ELAIS-N1 237.9 247.9 52.441 57.526  slphotdr4
HELP_tap_irsa_slphotdr4.csh GAMA-12 172.3 187.3 -3.474 2.518 slphotdr4
HELP_tap_irsa_slphotdr4.csh GAMA-09 127.2 142.2 -2.468 3.485 slphotdr4
HELP_tap_irsa_slphotdr4.csh Lockman-SWIRE 154.8 167.7 55.019 60.819 slphotdr4
HELP_tap_irsa_slphotdr4.csh EGS 212.4 217.5 51.155 54.234 slphotdr4
HELP_tap_irsa_slphotdr4.csh ELAIS-S1 6.4 11.2 -45.523 -41.603  slphotdr4
HELP_tap_irsa_slphotdr4.csh AKARI-NEP 264.6 275.3 64.484 68.471  slphotdr4
HELP_tap_irsa_slphotdr4.csh ELAIS-N2 246.1 252.3 39.090 42.950 slphotdr4
HELP_tap_irsa_slphotdr4.csh xFLS 255.6 262.5 57.917 60.768  slphotdr4
HELP_tap_irsa_slphotdr4.csh Herschel-Stripe-82 348.4 36.2 -9.117 8.856 slphotdr4
HELP_tap_irsa_slphotdr4.csh NGP 189.9 209.2 21.692 36.088  slphotdr4
HELP_tap_irsa_slphotdr4.csh SGP 337.2 26.9 -35.619 -24.512  slphotdr4
HELP_tap_irsa_slphotdr4.csh AKARI-SEP 66.2 75.4 -55.887 -51.682  slphotdr4
HELP_tap_irsa_slphotdr4.csh SPIRE-NEP 263.7 266.4 68.553 69.440  slphotdr4
HELP_tap_irsa_slphotdr4.csh SSDF 357.8 18.5 -60.499 -48.534  slphotdr4
HELP_tap_irsa_slphotdr4.csh HDF-N 188.1 190.4 6.0 1.760 slphotdr4
HELP_tap_irsa_slphotdr4.csh XMM-13hr 202.9 204.4 37.379 38.452  slphotdr4

