#!/bin/bash
# this script automatically generated by make_get_files_script.csh
curl -o AKARI-NEP_slphotdr4.fits -v http://irsa.ipac.caltech.edu:80/TAP/async/1660894/results/result
curl -o AKARI-SEP_slphotdr4.fits -v http://irsa.ipac.caltech.edu:80/TAP/async/1660902/results/result
curl -o Bootes_slphotdr4.fits -v http://irsa.ipac.caltech.edu:80/TAP/async/1662433/results/result
curl -o CDFS-SWIRE_slphotdr4.fits -v http://irsa.ipac.caltech.edu:80/TAP/async/1660887/results/result
curl -o COSMOS_slphotdr4.fits -v http://irsa.ipac.caltech.edu:80/TAP/async/1662228/results/result
curl -o EGS_slphotdr4.fits -v http://irsa.ipac.caltech.edu:80/TAP/async/1660657/results/result
curl -o ELAIS-N1_slphotdr4.fits -v http://irsa.ipac.caltech.edu:80/TAP/async/1662468/results/result
curl -o ELAIS-N2_slphotdr4.fits -v http://irsa.ipac.caltech.edu:80/TAP/async/1660895/results/result
curl -o ELAIS-S1_slphotdr4.fits -v http://irsa.ipac.caltech.edu:80/TAP/async/1660893/results/result
curl -o GAMA-09_slphotdr4.fits -v http://irsa.ipac.caltech.edu:80/TAP/async/1660889/results/result
curl -o GAMA-12_slphotdr4.fits -v http://irsa.ipac.caltech.edu:80/TAP/async/1660888/results/result
curl -o GAMA-15_slphotdr4.fits -v http://irsa.ipac.caltech.edu:80/TAP/async/1662454/results/result
curl -o HDF-N_slphotdr4.fits -v http://irsa.ipac.caltech.edu:80/TAP/async/1663677/results/result
curl -o Herschel-Stripe-82_slphotdr4.fits -v http://irsa.ipac.caltech.edu:80/TAP/async/1660899/results/result
curl -o Lockman-SWIRE_slphotdr4.fits -v http://irsa.ipac.caltech.edu:80/TAP/async/1660892/results/result
curl -o NGP_slphotdr4.fits -v http://irsa.ipac.caltech.edu:80/TAP/async/1660900/results/result
curl -o SA13_slphotdr4.fits -v http://irsa.ipac.caltech.edu:80/TAP/async/1664409/results/result
curl -o SGP_slphotdr4.fits -v http://irsa.ipac.caltech.edu:80/TAP/async/1660901/results/result
curl -o SPIRE-NEP_slphotdr4.fits -v http://irsa.ipac.caltech.edu:80/TAP/async/1660905/results/result
curl -o SSDF_slphotdr4.fits -v http://irsa.ipac.caltech.edu:80/TAP/async/1663704/results/result
curl -o XMM-13hr_slphotdr4.fits -v http://irsa.ipac.caltech.edu:80/TAP/async/1660908/results/result
curl -o XMM-LSS_slphotdr4.fits -v http://irsa.ipac.caltech.edu:80/TAP/async/1662233/results/result
curl -o xFLS_slphotdr4.fits -v http://irsa.ipac.caltech.edu:80/TAP/async/1660896/results/result
